[versions]
acra = "5.11.3"
androidsvg-aar = "1.4"
android-application = "8.7.3"
apollo = "4.0.0"
androidx-media3 = "1.6.0-beta01"
androidx-test = "1.6.1"
androidx-test-runner = "1.6.2"
androidx-test-ext-junit = "1.2.1"
androidx-test-ext-truth = "1.6.0"
auto-service = "1.1.1"
constraintlayout = "2.2.0"
core = "4.6.2"
core-ktx = "1.15.0"
ffmpegmediametadataretriever = "1.0.19"
glide = "4.16.0"
junit = "4.13.2"
kotlin = "2.1.0"
kotlinx-coroutines-android = "1.10.1"
kotlinx-serialization = "1.7.2"
ksp = "2.0.21-1.0.26"
leanback = "1.1.0-rc02"
leanback-preference = "1.1.0-rc01"
leanback-tab = "1.1.0-beta01"
lifecycle-process = "2.8.7"
material = "1.12.0"
mockito-core = "5.9.0"
mockito-kotlin = "5.2.1"
parcelable-core = "0.9.0"
preference-ktx-version = "1.2.1"
previewseekbar = "3.1.1"
previewseekbar-media3 = "1.1.1.0"
room = "2.6.1"
swiperefreshlayout = "1.1.0"
zoomlayout = "1.9.0"

[libraries]
acra-dialog = { module = "ch.acra:acra-dialog", version.ref = "acra" }
acra-http = { module = "ch.acra:acra-http", version.ref = "acra" }
acra-limiter = { module = "ch.acra:acra-limiter", version.ref = "acra" }
androidsvg-aar = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg-aar" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-process" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-process" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-ext-truth" }

androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-leanback-preference = { module = "androidx.leanback:leanback-preference", version.ref = "leanback-preference" }
androidx-leanback-tab = { module = "androidx.leanback:leanback-tab", version.ref = "leanback-tab" }
androidx-media3-effect = { module = "androidx.media3:media3-effect", version.ref = "androidx-media3" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "androidx-media3" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "androidx-media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
apollo-compiler = { module = "com.apollographql.apollo:apollo-compiler", version.ref = "apollo" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
core = { module = "io.noties.markwon:core", version.ref = "core" }
ffmpegmediametadataretriever-core = { module = "com.github.wseemann:FFmpegMediaMetadataRetriever-core", version.ref = "ffmpegmediametadataretriever" }
ffmpegmediametadataretriever-native = { module = "com.github.wseemann:FFmpegMediaMetadataRetriever-native", version.ref = "ffmpegmediametadataretriever" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
parcelable-core = { module = "com.chrynan.parcelable:parcelable-core", version.ref = "parcelable-core" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx-version" }
previewseekbar = { module = "com.github.rubensousa:previewseekbar", version.ref = "previewseekbar" }
previewseekbar-media3 = { module = "com.github.rubensousa:previewseekbar-media3", version.ref = "previewseekbar-media3" }
zoomlayout = { module = "com.otaliastudios:zoomlayout", version.ref = "zoomlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
